In [6]:
import torch
import numpy as np

## Tensor from python and numpy
We can construct a tensor directly from some common python iterables, such as list and tuple nested iterables can also be handled as long as the dimensions are compatible

In [3]:
a = [0, 1, 2]
# list -> tensor
a_tensor = torch.tensor(a)
a_tensor

tensor([0, 1, 2])

In [4]:
b = ((1.0, 1.1), (1.2, 1.3))
# tuple -> tensor
b_tensor = torch.tensor(b)
b_tensor

tensor([[1.0000, 1.1000],
        [1.2000, 1.3000]])

In [7]:
c = np.ones([2,3])
# numpy array -> tensor
c_tensor = torch.tensor(c)
c_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

## Zeros, Ones, Empty tensors

In [12]:
# ones
x = torch.ones(5)
print(x)
print()
x1 = torch.ones([5,3])
print(x1)

tensor([1., 1., 1., 1., 1.])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [26]:
# zeros
y = torch.zeros(5)
print(y)
print()
y1 = torch.zeros([5,3])
print(y1)

tensor([0., 0., 0., 0., 0.])

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [21]:
# empty
z = torch.empty(5)
print(z)
print()
z1 = torch.empty([5,3])
print(z1)
print()
z2 = torch.empty([1, 1, 5])
print(z2)

tensor([0., 0., 0., 0., 0.])

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

tensor([[[0., 0., 0., 0., 0.]]])


`.empty()` does not always return zeros, but seemingly random numbers. Unlike `.zeros()`, which initialises the elements of the tensor with zeros, `.empty()` just allocates the memory. It is hence a bit faster if you are looking to just create a tensor.

## Creating random tensors and tensors like other tensors

In [28]:
# Uniform dist
u = torch.rand([2,3])
print(u)

tensor([[0.4108, 0.3167, 0.8838],
        [0.1632, 0.5353, 0.9841]])


In [30]:
# normal dist
n = torch.randn([2,3])
print(n)

tensor([[-0.3203,  0.1340,  0.5702],
        [ 0.0492,  0.4280,  0.5327]])


There are also constructors that allow us to construct a tensor according to the above constructors, but with dimensions equal to another tensor.

In [31]:
zl = torch.zeros_like(u)
print(zl)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [32]:
rl = torch.rand_like(zl)
print(rl)

tensor([[0.0337, 0.1152, 0.4512],
        [0.6057, 0.6704, 0.2001]])


## Reproducibility

### PyTorch Random Number Generator (RNG)

In [33]:
torch.manual_seed(0)

### python seed 

In [34]:
import random
random.seed(0)

### Numpy seed

In [35]:
np.random.seed(0)

Defining a function called `set_seed` 

In [37]:
def set_seed(seed=None, seed_torch=True):
    """
    Function that controls randomness. Numpy and random modules must be imported

    Args:
        seed: int
            A non-negative integer that defines the random state. Default is 'None'.
        seed_torch: bool
            If 'True' sets the random seed for pytorch tensors, so pytorch module 
            must be imported. Default is 'True'

    Returns:
        Nothing
    """

    if seed is None:
        seed = np.random.choice(2**32)
    random.seed(seed)
    np.random.seed(seed)

    if seed_torch:
        torch.manual_seed(seed)
        ## for mps
        torch.mps.manual_seed(seed)
        ## for cuda
        # torch.cuda.manual_seed_all(seed)
        # torch.cuda.manual_seed(seed)
        # torch.backends.cudnn.benchmark = False
        # torch.backends.cudnn.deterministic = True

    print(f"Random seed {seed} has been set.")

In [38]:
def simplefun(seed=True, my_seed=None):
  """
  Helper function to verify effectiveness of set_seed attribute

  Args:
    seed: Boolean
      Specifies if seed value is provided or not
    my_seed: Integer
      Initializes seed to specified value

  Returns:
    Nothing
  """
  if seed:
    set_seed(seed=my_seed)

  # uniform distribution
  a = torch.rand(1, 3)
  # normal distribution
  b = torch.randn(3, 4)

  print("Tensor a: ", a)
  print("Tensor b: ", b)

In [39]:
simplefun(seed=True, my_seed=0)

Random seed 0 has been set.
Tensor a:  tensor([[0.4963, 0.7682, 0.0885]])
Tensor b:  tensor([[ 0.3643,  0.1344,  0.1642,  0.3058],
        [ 0.2100,  0.9056,  0.6035,  0.8110],
        [-0.0451,  0.8797,  1.0482, -0.0445]])


In [40]:
simplefun(seed=False, my_seed=0)

Tensor a:  tensor([[0.0362, 0.1852, 0.3734]])
Tensor b:  tensor([[-0.9528,  0.3717,  0.4087,  1.4214],
        [ 0.1494, -0.6709, -0.2142, -0.4320],
        [-0.7079, -0.1064, -1.2427, -0.4762]])


In [42]:
simplefun(seed=True, my_seed=None)

Random seed 1608637542 has been set.
Tensor a:  tensor([[0.4035, 0.9807, 0.1538]])
Tensor b:  tensor([[-0.0153,  0.1611,  0.3617, -0.7011],
        [-1.2480,  1.7167, -0.6075, -1.1244],
        [ 0.3741, -0.8877, -0.2190,  1.3018]])


## Numpy-like number ranges
The .arange() and .linspace() behave how you would expect them to if you are familar with numpy.

In [43]:
a = np.arange(0,10, step=1)
print(a)
print()
b = torch.arange(0,10, step=1)
print(b)

[0 1 2 3 4 5 6 7 8 9]

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [47]:
c = np.linspace(0,5, num=11)
print(c)
print()
d = torch.linspace(0,5, steps=11)
print(d)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000])


## Exercise

Below you will find some incomplete code. Fill in the missing code to construct the specified tensors.

We want the tensors:

- A: 20 by 21 tensor consisting of ones

- B: a tensor with elements equal to the elements of numpy array Z

- C: a tensor with the same number of elements as A but with values from uniform distribution

- D: a 1D tensor containing the even numbers between 4 and 40 inclusive.

In [48]:
np.vander([1,2,3])

array([[1, 1, 1],
       [4, 2, 1],
       [9, 3, 1]])

In [49]:
np.array([
    [1**2, 1**1, 1**0],
    [2**2, 2**1, 2**0],
    [3**2, 3**1, 3**0]
])

array([[1, 1, 1],
       [4, 2, 1],
       [9, 3, 1]])

In [50]:
np.vander([1,2,3], 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1]])

In [51]:
np.array([
    [1**3, 1**2, 1**1, 1**0],
    [2**3, 2**2, 2**1, 2**0],
    [3**3, 3**2, 3**1, 3**0]
])

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1]])

### Helper function to test exercise 1

In [68]:
# @title Helper Functions

def checkExercise1(A, B, C, D):
  """
  Helper function for checking Exercise 1.

  Args:
    A: torch.Tensor
      Torch Tensor of shape (20, 21) consisting of ones.
    B: torch.Tensor
      Torch Tensor of size([3,4])
    C: torch.Tensor
      Torch Tensor of size([20,21])
    D: torch.Tensor
      Torch Tensor of size([19])

  Returns:
    Nothing.
  """
  assert torch.equal(A.to(int),torch.ones(20, 21).to(int)), "Got: {A} \n Expected: {torch.ones(20, 21)} (shape: {torch.ones(20, 21).shape})"
  assert np.array_equal(B.numpy(),np.vander([1, 2, 3], 4)), "Got: {B} \n Expected: {np.vander([1, 2, 3], 4)} (shape: {np.vander([1, 2, 3], 4).shape})"
  assert C.shape == (20, 21), "Got: {C} \n Expected (shape: {(20, 21)})"
  assert torch.equal(D, torch.arange(4, 41, step=2)), "Got {D} \n Expected: {torch.arange(4, 41, step=2)} (shape: {torch.arange(4, 41, step=2).shape})"
  print("All correct")

In [73]:
def tensor_creation(Z):
    """
    A function that creates various tensors.
    
    Args:
    Z: numpy.ndarray
      An array of shape (3,4)
    
    Returns:
    A : Tensor
      20 by 21 tensor consisting of ones
    B : Tensor
      A tensor with elements equal to the elements of numpy array Z
    C : Tensor
      A tensor with the same number of elements as A but with values ∼U(0,1)
    D : Tensor
      A 1D tensor containing the even numbers between 4 and 40 inclusive.
    """
    #################################################
    ## TODO for students: fill in the missing code
    ## from the first expression
    # raise NotImplementedError("Student exercise: say what they should have done")
    #################################################
    A = torch.ones([20,21])
    B = torch.tensor(Z)
    # same 
    # B = torch.asarray(Z)
    C = torch.rand_like(A)
    D = torch.arange(4,41,2)
    
    return A, B, C, D

In [74]:
# numpy array to copy later
Z = np.vander([1, 2, 3], 4)

# Uncomment below to check your function!
A, B, C, D = tensor_creation(Z)
checkExercise1(A, B, C, D)

All correct


True