In [1]:
import torch
import numpy as np

# Operations in PyTorch

## Tensor-Tensor operations

In [2]:
a = torch.ones(5, 3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [3]:
b = torch.rand(5, 3)
b

tensor([[0.2399, 0.7858, 0.7764],
        [0.6358, 0.6567, 0.3133],
        [0.7004, 0.6453, 0.3354],
        [0.6292, 0.7800, 0.6569],
        [0.8808, 0.1326, 0.6250]])

In [4]:
c = torch.empty(5, 3)
c

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
d = torch.empty(5, 3)
d

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [11]:
# torch.add(input, other, *, alpha=1, out=None) → Tensor
# Adds other, scaled by alpha, to input.
torch.add(a, b, alpha=1, out=c)
print(c)

tensor([[1.2399, 1.7858, 1.7764],
        [1.6358, 1.6567, 1.3133],
        [1.7004, 1.6453, 1.3354],
        [1.6292, 1.7800, 1.6569],
        [1.8808, 1.1326, 1.6250]])


In [13]:
print(a+b)

tensor([[1.2399, 1.7858, 1.7764],
        [1.6358, 1.6567, 1.3133],
        [1.7004, 1.6453, 1.3354],
        [1.6292, 1.7800, 1.6569],
        [1.8808, 1.1326, 1.6250]])


In [12]:
# torch.mul(input, other, *, out=None)
torch.multiply(a, b, out=d)
print(d)

tensor([[0.2399, 0.7858, 0.7764],
        [0.6358, 0.6567, 0.3133],
        [0.7004, 0.6453, 0.3354],
        [0.6292, 0.7800, 0.6569],
        [0.8808, 0.1326, 0.6250]])


In [14]:
print(a*b)

tensor([[0.2399, 0.7858, 0.7764],
        [0.6358, 0.6567, 0.3133],
        [0.7004, 0.6453, 0.3354],
        [0.6292, 0.7800, 0.6569],
        [0.8808, 0.1326, 0.6250]])


## Tensor Methods

In [18]:
x = torch.rand(3,4)
x

tensor([[0.5072, 0.0073, 0.8039, 0.2941],
        [0.3120, 0.0035, 0.7525, 0.0713],
        [0.6252, 0.0487, 0.7941, 0.4842]])

In [25]:
print(f"Sum of every element of x: {x.sum()}")

print(f"Sum of the columns of x: {x.sum(axis=0)}") # 4 cols

print(f"Sum of the rows of x: {x.sum(axis=1)}") # 3 rows

Sum of every element of x: 4.70390510559082
Sum of the columns of x: tensor([1.4444, 0.0594, 2.3505, 0.8495])
Sum of the rows of x: tensor([1.6125, 1.1393, 1.9522])


In [24]:
print(f"Mean value of all elements of x {x.mean()}")
print(f"Mean values of the columns of x {x.mean(axis=0)}")
print(f"Mean values of the rows of x {x.mean(axis=1)}")

Mean value of all elements of x 0.39199209213256836
Mean values of the columns of x tensor([0.4815, 0.0198, 0.7835, 0.2832])
Mean values of the rows of x tensor([0.4031, 0.2848, 0.4880])


## Matrix Operations

The `@` symbol is overridden to represent matrix multiplication. You can also use `torch.matmul()` to multiply tensors. 

For dot multiplication, you can use `torch.dot()`, or manipulate the axes of your tensors and do matrix multiplication.

Transposes of 2D tensors are obtained using `torch.t()` or `Tensor.T`. Note the lack of brackets for Tensor.T - it is an attribute, not a method.

## Exercise: Matrix Multiplication

In [29]:
def simple_operations(a1: torch.Tensor, a2: torch.Tensor, a3: torch.Tensor):
    """
    Helper function to demonstrate simple operations
    i.e., Multiplication of tensor a1 with tensor a2 and then add it with tensor a3
    
    Args:
    a1: Torch tensor
      Tensor of size ([2,2])
    a2: Torch tensor
      Tensor of size ([2,2])
    a3: Torch tensor
      Tensor of size ([2,2])
    
    Returns:
    answer: Torch tensor
      Tensor of size ([2,2]) resulting from a1 multiplied with a2, added with a3
    """
    ################################################
    ## TODO for students:  complete the first computation using the argument matricies
    # raise NotImplementedError("Student exercise: fill in the missing code to complete the operation")
    ################################################
    #
    answer = a1 @ a2 + a3
    return answer

In [30]:
# init our tensors
a1 = torch.tensor([[2, 4], [5, 7]])
a2 = torch.tensor([[1, 1], [2, 3]])
a3 = torch.tensor([[10, 10], [12, 1]])

A = simple_operations(a1, a2, a3)
print(A)

tensor([[20, 24],
        [31, 27]])


In [31]:
def dot_product(b1: torch.Tensor, b2: torch.Tensor):
    ###############################################
    ## TODO for students:  complete the first computation using the argument matricies
    # raise NotImplementedError("Student exercise: fill in the missing code to complete the operation")
    ###############################################
    """
    Helper function to demonstrate dot product operation
    Dot product is an algebraic operation that takes two equal-length sequences
    (usually coordinate vectors), and returns a single number.
    Geometrically, it is the product of the Euclidean magnitudes of the
    two vectors and the cosine of the angle between them.
    
    Args:
    b1: Torch tensor
      Tensor of size ([3])
    b2: Torch tensor
      Tensor of size ([3])
    
    Returns:
    product: Tensor
      Tensor of size ([1]) resulting from b1 scalar multiplied with b2
    """
    # Use torch.dot() to compute the dot product of two tensors
    product = torch.dot(b1,b2)
    return product

In [33]:
b1 = torch.tensor([3, 5, 7])
b2 = torch.tensor([2, 4, 8])

b = dot_product(b1, b2)
print(b)

tensor(82)
