In [2]:
import torch
import numpy as np

## Manipulating Tensors in Pytorch

### Indexing
Just as in numpy, elements in a tensor can be accessed by index. As in any numpy array, the first element has index 0 and ranges are specified to include the first to last_element-1. We can access elements according to their relative position to the end of the list by using negative indices. Indexing is also referred to as slicing.

For example, [-1] selects the last element; [1:3] selects the second and the third elements, and [:-2] will select all elements excluding the last and second-to-last elements.

In [3]:
x = torch.arange(0,10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
print(x[-1])
print(x[1:3])
print(x[:-2])

tensor(9)
tensor([1, 2])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


When we have multidimensional tensors, indexing rules work the same way as NumPy.

In [7]:
x = torch.rand(1, 2, 3, 4, 5)
x

tensor([[[[[0.6052, 0.9500, 0.6122, 0.8043, 0.8604],
           [0.4410, 0.3089, 0.3415, 0.1730, 0.4359],
           [0.1127, 0.1262, 0.3026, 0.7474, 0.0304],
           [0.3562, 0.1015, 0.6013, 0.0753, 0.3767]],

          [[0.7739, 0.6223, 0.4113, 0.5697, 0.4754],
           [0.8438, 0.4443, 0.3628, 0.8503, 0.0903],
           [0.9975, 0.8044, 0.1481, 0.0114, 0.1434],
           [0.0310, 0.6013, 0.6739, 0.7435, 0.7067]],

          [[0.5022, 0.0317, 0.7890, 0.6018, 0.9796],
           [0.1295, 0.8435, 0.4962, 0.5049, 0.2748],
           [0.0506, 0.2356, 0.3276, 0.3444, 0.6352],
           [0.2016, 0.6140, 0.0890, 0.5393, 0.0902]]],


         [[[0.1199, 0.3958, 0.5205, 0.9517, 0.1954],
           [0.8870, 0.4473, 0.8225, 0.3530, 0.8856],
           [0.5188, 0.0591, 0.7742, 0.7723, 0.6346],
           [0.4128, 0.6335, 0.9946, 0.2659, 0.8958]],

          [[0.7701, 0.5681, 0.2744, 0.7417, 0.5187],
           [0.8333, 0.7371, 0.7043, 0.0288, 0.0458],
           [0.6413, 0.1105, 0.9185, 

In [11]:
print(f" shape of x:{x.shape}")
print(f" shape of x[0]:{x[0].shape}")
print(f" shape of x[0][0]:{x[0][0].shape}")
print(f" shape of x[0][0][0]:{x[0][0][0].shape}")

 shape of x:torch.Size([1, 2, 3, 4, 5])
 shape of x[0]:torch.Size([2, 3, 4, 5])
 shape of x[0][0]:torch.Size([3, 4, 5])
 shape of x[0][0][0]:torch.Size([4, 5])


### Flatten and reshape

There are various methods for reshaping tensors. It is common to have to express 2D data in 1D format. Similarly, it is also common to have to reshape a 1D tensor into a 2D tensor. We can achieve this with the .flatten() and .reshape() methods.

In [15]:
z = torch.arange(12)
print(f"shape of z:{z.shape}")
z

shape of z:torch.Size([12])


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
# reshaping z
z = z.reshape(6,2)
print(f"shape of z:{z.shape}")
z

shape of z:torch.Size([6, 2])


tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [17]:
# 2D -> 1D
z = z.flatten()
print(f"shape of z:{z.shape}")
print(f"Flattened z: \n {z}")

shape of z:torch.Size([12])
Flattened z: 
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [18]:
# and back to 2D
z = z.reshape(3, 4)
print(f"shape of z:{z.shape}")
print(f"Reshaped (3x4) z: \n {z}")

shape of z:torch.Size([3, 4])
Reshaped (3x4) z: 
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


You will also see the .view() methods used a lot to reshape tensors. There is a subtle difference between .view() and .reshape(), though for now we will just use .reshape().

### Squeezing tensors

When processing batches of data, you will quite often be left with singleton dimensions. E.g., [1,10] or [256, 1, 3]. 

This dimension can quite easily mess up your matrix operations if you don’t plan on it being there.

In order to compress tensors along their singleton dimensions we can use the .squeeze() method. We can use the .unsqueeze() method to do the opposite.

In [21]:
x = torch.randn(1, 10)
print(x)
print(f" shape of x:{x.shape}\n")

# printing the zeroth element of the tensor will not give us the first number!
print(f"x[0]: {x[0]}")

tensor([[ 0.1120, -0.3482, -1.2162,  0.9048, -0.3318, -0.8544,  0.4216, -0.3407,
          2.2298, -0.3475]])
 shape of x:torch.Size([1, 10])

x[0]: tensor([ 0.1120, -0.3482, -1.2162,  0.9048, -0.3318, -0.8544,  0.4216, -0.3407,
         2.2298, -0.3475])


Because of that pesky singleton dimension, x[0] gave us the first row instead!

In [24]:
# Let's get rid of that singleton dimension and see what happens now
x = x.squeeze(dim=0)
print(x)
print(f" shape of x after removing dimension:{x.shape}\n")
print(f"x[0]: {x[0]}")

tensor([ 0.1120, -0.3482, -1.2162,  0.9048, -0.3318, -0.8544,  0.4216, -0.3407,
         2.2298, -0.3475])
 shape of x after removing dimension:torch.Size([10])

x[0]: 0.11200101673603058


In [26]:
# Adding singleton dimensions works a similar way, and is often used when tensors
# being added need same number of dimensions

y = torch.randn(5, 5)
print(y)
print(f"Shape of y: {y.shape}\n")

# lets insert a singleton dimension
y = y.unsqueeze(dim=1)
print(f"Shape of y after adding dimension: {y.shape}")

tensor([[ 0.9925,  0.9772, -0.9462, -0.6351, -0.1659],
        [ 0.4342,  0.1210,  0.6499, -0.1199,  0.6560],
        [-0.3157,  0.4387, -1.3532,  0.4942, -0.6562],
        [-0.2433, -1.1493, -2.1141,  0.2158,  0.6278],
        [ 0.3916, -1.5136, -0.5789, -0.1252,  1.7774]])
Shape of y: torch.Size([5, 5])

Shape of y after adding dimension: torch.Size([5, 1, 5])


### Permutation

Sometimes our dimensions will be in the wrong order! For example, we may be dealing with RGB images with dim [3 x 48 x 64], but our pipeline expects the colour dimension to be the last dimension, i.e., [48 x 64 x 3]
. To get around this we can use the .permute() method.

In [28]:
# `x` has dimensions [color,image_height,image_width]
x = torch.rand(3, 48, 64)
print(f" shape of x:{x.shape}\n")

# We want to permute our tensor to be [ image_height , image_width , color ]
x = x.permute(1, 2, 0)

# permute(1,2,0) means:
# The 0th dim of my new tensor = the 1st dim of my old tensor
# The 1st dim of my new tensor = the 2nd
# The 2nd dim of my new tensor = the 
print(f" shape of x after changing the dimensions order: {x.shape}\n")

 shape of x:torch.Size([3, 48, 64])

 shape of x after changing the dimensions order: torch.Size([48, 64, 3])



You may also see .transpose() used. This works in a similar way as permute, but can only swap two dimensions at once.

### Concatenation

In this example, we concatenate two matrices along rows (axis 0, the first element of the shape) vs. columns (axis 1, the second element of the shape). 

We can see that the first output tensor’s axis-0 length (6) is the sum of the two input tensors’ axis-0 lengths (3+3); 

While the second output tensor’s axis-1 length (8) is the sum of the two input tensors’ axis-1 lengths (4+4).

In [29]:
# Create two tensors of the same shape
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(x)
print(f" shape of x:{x.shape}\n")
print(y)
print(f" shape of y:{y.shape}\n")

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
 shape of x:torch.Size([3, 4])

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])
 shape of y:torch.Size([3, 4])



In [33]:
# Concatenate along rows
cat_rows = torch.cat((x, y), dim=0)
print(f"Concatenated by rows, shape: {cat_rows.shape} \n {cat_rows}")

Concatenated by rows, shape: torch.Size([6, 4]) 
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])


In [34]:
# Concatenate along columns
cat_cols = torch.cat((x, y), dim=1)
print(f"Concatenated by columns, shape: {cat_cols.shape} \n {cat_cols}")

Concatenated by columns, shape: torch.Size([3, 8]) 
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


### Conversion to Other Python Objects

Converting a tensor to a numpy.ndarray, or vice versa, is easy, and the converted result does not share memory. This minor inconvenience is quite important: when you perform operations on the CPU or GPUs, you do not want to halt computation, waiting to see whether the NumPy package of Python might want to be doing something else with the same chunk of memory.

When converting to a NumPy array, the information being tracked by the tensor will be lost, i.e., the computational graph. 

In [35]:
x = torch.randn(5)
print(f"x: {x}  |  x type:  {x.type()}")

y = x.numpy()
print(f"y: {y}  |  y type:  {type(y)}")

z = torch.tensor(y)
print(f"z: {z}  |  z type:  {z.type()}")

x: tensor([-0.9612, -1.3004, -0.9955, -0.1614,  1.0023])  |  x type:  torch.FloatTensor
y: [-0.9612143  -1.3004     -0.99553746 -0.16137064  1.002297  ]  |  y type:  <class 'numpy.ndarray'>
z: tensor([-0.9612, -1.3004, -0.9955, -0.1614,  1.0023])  |  z type:  torch.FloatTensor


To convert a size-1 tensor to a Python scalar, we can invoke the item function or Python’s built-in functions.

In [36]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

torch.numel() is an easy way of finding the number of elements in a tensor.

In [38]:
cat_rows

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [39]:
n_elements = torch.numel(cat_rows)
n_elements

24

## Exercise

In [9]:
def functionA(my_tensor1, my_tensor2):
      """
      This function takes in two 2D tensors `my_tensor1` and `my_tensor2`
      and returns the column sum of
      `my_tensor1` multiplied by the sum of all the elmements of `my_tensor2`,
      i.e., a scalar.
    
      Args:
        my_tensor1: torch.Tensor
        my_tensor2: torch.Tensor
    
      Retuns:
        output: torch.Tensor
          The multiplication of the column sum of `my_tensor1` by the sum of
          `my_tensor2`.
      """
      ################################################
      ## TODO for students: complete functionA
      # raise NotImplementedError("Student exercise: complete function A")
      ################################################
      # TODO multiplication the sum of the tensors
      output = my_tensor1.sum(dim=1) * my_tensor2.sum(dim=None)
    
      return output


In [12]:
print(
    functionA(
    torch.tensor([[1, 1], [1, 1]]), 
    torch.tensor([[1, 2, 3], [1, 2, 3]])
    )
)

tensor([24, 24])


In [11]:
# a = torch.tensor([[1, 1], [1, 1]])
# a

# b = torch.tensor([[1, 2, 3], [1, 2, 3]])
# b

# # column sum
# a_sum = a.sum(dim=1)
# a_sum

# # sum of all elements of b
# b_sum = b.sum()
# b_sum

# a_sum * b_sum

In [28]:
def functionB(my_tensor):
    """
    This function takes in a square matrix `my_tensor` and returns a 2D tensor
    consisting of a flattened `my_tensor` with the index of each element
    appended to this tensor in the row dimension.
    
    Args:
    my_tensor: torch.Tensor
    
    Returns:
    output: torch.Tensor
      Concatenated tensor.
    """
    ################################################
    ## TODO for students: complete functionB
    # raise NotImplementedError("Student exercise: complete function B")
    ################################################
    # TODO flatten the tensor `my_tensor`
    my_tensor = my_tensor.flatten()
    # TODO create the idx tensor to be concatenated to `my_tensor`
    idx_tensor = torch.arange(torch.numel(my_tensor))
    # TODO concatenate the two tensors
    my_tensor = my_tensor.unsqueeze(dim=1)
    idx_tensor = idx_tensor.unsqueeze(dim=1)
    output = torch.cat((idx_tensor,my_tensor), dim=1)
    
    return output

In [29]:
print(
    functionB(
        torch.tensor([[2, 3], [-1, 10]])
    )
)

tensor([[ 0,  2],
        [ 1,  3],
        [ 2, -1],
        [ 3, 10]])


In [30]:
# a = torch.tensor([[2, 3], [-1, 10]])
# a

# # flattening
# a_flat = a.flatten()
# # creating column matrix
# a_flat_col = a_flat.unsqueeze(dim=1)
# a_flat_col

# # finding total elements in a
# n_elements = torch.numel(a)
# # creating a 1 dim matrix with the elements
# a_ind = torch.arange(n_elements)
# # creating a 2 dim matrix by adding a column
# a_ind_col = a_ind.unsqueeze(dim=1)
# a_ind_col

# # concatenating the column matrices
# final_a = torch.concat((a_ind_col, a_flat_col), dim=1)
# final_a

In [60]:
def functionC(my_tensor1, my_tensor2):
  """
  This function takes in two 2D tensors `my_tensor1` and `my_tensor2`.
  If the dimensions allow it, it returns the
  elementwise sum of `my_tensor1`-shaped `my_tensor2`, and `my_tensor2`;
  else this function returns a 1D tensor that is the concatenation of the
  two tensors.

  Args:
    my_tensor1: torch.Tensor
    my_tensor2: torch.Tensor

  Returns:
    output: torch.Tensor
      Concatenated tensor.
  """
  ################################################
  ## TODO for students: complete functionB
  # raise NotImplementedError("Student exercise: complete function C")
  ################################################
  # TODO check we can reshape `my_tensor2` into the shape of `my_tensor1`
  if torch.numel(my_tensor1) == torch.numel(my_tensor2):
    # TODO reshape `my_tensor2` into the shape of `my_tensor1`
    my_tensor2 = my_tensor2.reshape(my_tensor1.shape)
    # TODO sum the two tensors
    output = my_tensor1 + my_tensor2
  else:
    # TODO flatten both tensors
    my_tensor1 = my_tensor1.flatten()
    my_tensor2 = my_tensor2.flatten()
    # TODO concatenate the two tensors in the correct dimension
    output = torch.cat((my_tensor1, my_tensor2), dim=0)

  return output

In [61]:
print(
    functionC(
        torch.tensor([[1, -1], [-1, 3]]), 
        torch.tensor([[2, 3, 0, 2]])
    )
)


tensor([[ 3,  2],
        [-1,  5]])


In [62]:
print(
    functionC(
        torch.tensor([[1, -1], [-1, 3]]), 
        torch.tensor([[2, 3, 0]])
    )
)

tensor([ 1, -1, -1,  3,  2,  3,  0])


In [65]:
# d = torch.tensor([[1, -1], [-1, 3]])
# d

# e = torch.tensor([[2, 3, 0, 2]])
# e

# ## lementwise sum of d shaped e
# # reshaping e
# e = e.reshape(d.shape)
# e

# # elementwise sum
# s = d + e
# s

# d

# e = torch.tensor([[2, 3, 0]])
# e.shape

# e.squeeze(dim=0)

# if d.shape != e.shape:
#     d = d.flatten()
#     e = e.flatten()
#     con = torch.cat((d,e), dim=0)
# con